@ShopApp_HostAddress = http://localhost:5097

GET {{ShopApp_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ShopApp_HostAddress}}/api/product

###

GET {{ShopApp_HostAddress}}/api/product/46
